name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        ruby: [ '2.6', '2.7', '2.5', '2.4' ]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      env:
        LOSANT_SECRET: ${{ secrets.LOSANT_SECRET }}
        LOSANT_KEY: ${{ secrets.LOSANT_KEY }}
      run: bundle exec rake
